FROM centos:7 
RUN yum -y install httpd 
EXPOSE 80:80
CMD ["apachectl","-DFOREGROUND"]

## docker build -t nom_imagen:tags .

## docker run -d --name -p xx:xx nom_imagen:tags

## docker run -it --name -p xx:xx nom_imagen:tags

